language: go
go:
  - 1.8.x
  - 1.9.x
sudo: false

script:
  - export GOROOT=/usr/local/go
  - export GOPATH=$HOME/go
  - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  
install:
  - git clone https://github.com/opacey/dmgd $GOPATH/src/github.com/opacey/dmgd
  - cd $GOPATH/src/github.com/opacey/dmgd
  - go get -u github.com/Masterminds/glide
  - glide install
  - go install . ./cmd/...
  - cd $GOPATH/src/github.com/opacey/dmgd/blockchain
  - go test -v
